#!/usr/bin/env bash

set -euo pipefail
set -x

current_user=$(who am i | awk '{print $1}')
current_uid=$(id -u "$current_user")
current_gid=$(id -g "$current_user")

# Remove all ACLs
find wp-files | xargs setfacl --remove-all

# Updates ownership to www-data
chown -R 33:33 wp-files

# Allow user and group full access
setfacl -d -m u:"$current_uid":rwx -m g:"$current_gid":rwx wp-files
find wp-files | xargs setfacl -m u:"$current_uid":rwx -m g:"$current_gid":rwx
